@startuml Class
enum Gender {
    Male
    Female
    Other
}

class User {
    String id
    String name
    Gender gender
    DateTime dateOfBirth
    String email
    String phoneNumber
    Bool isActive
    DateTime creationTime
    String passwordHash

    void deactivateUser()
}

enum PaymentMethodType {
    In-store
    Visa
    Mastercard
    MoMo
}

class PaymentMethod {
    Int id
    PaymentMethodType type
    String? cardNumber
    Date? expiryDate
    DateTime creationTime
    Customer customer
    Order[] orders
}

enum DeliveryMethod {
    In-store
    Delivery
}

class Customer {
    PaymentMethod preferredPaymentMethod
    DeliveryMethod defaultDeliveryMethod
    String? defaultDeliveryAddress
    OrderItem[] cartItems
    Order[] placedOrders
}
User <|-- Customer
Customer *-- PaymentMethod

class Employee {
    Order[] processedOrders
}
User <|-- Employee

class ProductCategory {
    Int id
    String name
    String description
    Product[] products
}

class Product {
    String id
    Url imageUrl
    String name
    ProductCategory category
    String description
    Money price
    Int currentStock
    DateTime creationTime
}
ProductCategory o-- Product

enum OrderStatus {
    Processing
    Picking-up
    Delivering
    Delivered
    Done
    Canceled
    Returned
}

enum PaymentStatus {
    Pending
    Done
}

class Order {
    String id
    OrderItem[] items
    Money subTotal
    Money taxAmount
    Money shippingAmount
    Money otherAmount
    Money totalAmount
    Promotion[] appliedPromotions
    Customer customer
    DeliveryMethod deliveryMethod
    String? deliveryAddress
    PaymentMethod paymentMethod
    Seller seller
    OrderStatus orderStatus
    PaymentStatus paymentStatus
    DateTime creationTime
    DateTime? paymentFinishTime
    DateTime? finishTime
}
Customer o-- Order
Employee o-- Order
PaymentMethod o-- Order

class OrderItem {
    String orderId
    Product order
    String productId
    Product product
    Money unitPrice
    Int quantity
    Money totalPrice
}
Order *-- OrderItem
Product o-- OrderItem
Customer o-- OrderItem

class PromotionOrderItemReq {
    String promotionCode
    Promotion[] promotions
    Int productId
    Product product
    Int minimumQuantity
}

class Promotion {
    String code
    String name
    Double discountRate
    Money minimumSubTotal
    PromotionOrderItemReq[] orderItemRequirements
    DateTime creationDate
    DateTime expiryDate
    Order[] orders
}
Promotion *-- PromotionOrderItemReq
Promotion o-- Order
Promotion --o Order
@enduml