@startuml UseCases
left to right direction
:Customer: as c
:Seller: as s
:Manager: as m

rectangle System {
    c -- (View products)
    (View products) <|-- (Search products)
    (View products) <|-- (View product details)
    (View products) <|-- (Add to cart)
    (View product details) <|-- (Add to cart)

    c -- (View promotions)
    (View promotions) <|-- (Add to cart)
    (View promotions) <|-- (View promotion details)
    (View promotion details) <|-- (Add to cart)

    c -- (View cart)
    (View cart) <|-- (Place order)
    (Place order) --> (Select payment method)
    (Place order) --> (Select delivery method)
    (Place order) <|-- (Select promotions)

    c -- (Manage account)
    c -- (Login/Logout)
    (Login/Logout) <|-- (Register)

    s -- (Manage orders)
    m -- (Manage orders)
    (Manage orders) <|-- (Update order status)
    (Manage orders) <|-- (Confirm in-store payment)
    (Confirm in-store payment) --> (Generate receipt)
    (Manage orders) <|-- (Generate receipt)
    s -- (Customer support)

    m -- (Manage stock)
    m -- (Manage products)
    m -- (Manage product categories)
    m -- (Generate sales report)
}
@enduml