@startuml procurement
left to right direction

:Director: as d
:Finance: as f

:Production planner: as pp
:Production manager: as prm
pp <|-- prm

:Procurement manager: as pm
:Procurement specialist: as ps
ps <|-- pm

rectangle Procurement {
    pp -- (Manage Purchase Requisition)
    f -- (Approve Purchase Requisition)
    prm -- (Approve Purchase Requisition)
    (Approve Purchase Requisition) ..> (Manage Purchase Requisition) : <<extends>>

    ps -- (Manage Purchase Order)
    (Manage Purchase Order) <|.. (Update Purchase Order progress) : <<extends>>
    (Manage Purchase Order) <|.. (Attach Purchase Invoice) : <<extends>>
    f -- (Complete Purchase Order payment)
    (Complete Purchase Order payment) ..> (Manage Purchase Order) : <<includes>>

    pm -- (Manage Vendors)
    pm -- (Manage Supplys)

    pm -- (Generate Procurement Report)
    d -- (Generate Procurement Report)
}
@enduml