@startuml sales
left to right direction

:Director: as d

:Production manager: as pm

:Sales specialist: as s
:Sales manager: as sm
s <|-- sm

:Logistics specialist: as ls

rectangle Sales {
    s -- (Manage Sales Order)
    (Manage Sales Order) <|.. (Update Sales Order progress) : <<extends>>
    ls -- (Update Sales Order status)
    (Manage Sales Order) <|.. (Generate Sales Invoice) : <<extends>>

    sm -- (Generate Sales Report)
    d -- (Generate Sales Report)
    pm -- (Manage Products)
    sm -- (Manage Products)
    sm -- (Manage Retailers)
}
@enduml